fix(ci-cd): no audit

diff --git a/.github/workflows/code-verification.yaml b/.github/workflows/code-verification.yaml
--- a/.github/workflows/code-verification.yaml
+++ b/.github/workflows/code-verification.yaml
@@ -19,18 +19,21 @@ jobs:
           node-version: 22
           cache: npm
 
-      - name: Generate lockfile
+      - name: Install dependencies and generate lock file
         run: |
-          if [ -f package.json ]; then
-            echo "Generating package-lock.json..."
-            npm install --package-lock-only || exit 1
-          else
-            echo "Error: package.json not found. Cannot generate lockfile."
+          echo "Checking if lock file exists..."
+          if [ ! -f package.json ]; then
+            echo "Error: package.json not found. Cannot install dependencies."
             exit 1
           fi
 
-      - name: Install dependencies
-        run: npm ci --no-audit --no-fund
+          if [ ! -f package-lock.json ]; then
+            echo "package-lock.json not found. Generating it now..."
+            npm install --package-lock-only || exit 1
+          fi
+
+          echo "Installing dependencies..."
+          npm ci --no-audit --no-fund || exit 1
 
       - name: Run Lint
         run: npm run lint
